import { Currency } from "./types";

export const currencies: Record<string,Currency> = {
  "AED": {
    currencyCode: "AED",
    currencyName: "UAE Diram",
    icon: "🇦🇪",
  },
  "ARS": {
    currencyCode: "ARS",
    currencyName: "Argentine Peso",
    icon: "🇦🇷",
    exchangeRate: "-",
  },
  "AUD": {
    currencyCode: "AUD",
    currencyName: "Australian Dollar",
    icon: "🇦🇺",
    exchangeRate: "-",
  },
  "BGN": {
    currencyCode: "BGN",
    currencyName: "Bulgaria Lev",
    icon: "🇧🇬",
    exchangeRate: "-",
  },
  "BRL": {
    currencyCode: "BRL",
    currencyName: "Brazillian Real",
    icon: "🇧🇷",
    exchangeRate: "-",
  },
  "CAD": {
    currencyCode: "CAD",
    currencyName: "Canadian Dollar",
    icon: "🇨🇦",
    exchangeRate: "-",
  },
  "CHF": {
    currencyCode: "CHF",
    currencyName: "Swiss Franc",
    icon: "🇨🇭",
    exchangeRate: "-",
  },
  "CNY": {
    currencyCode: "CNY",
    currencyName: "Chinese Yuan",
    icon: "🇨🇳",
    exchangeRate: "-",
  },
  "CZK": {
    currencyCode: "CZK",
    currencyName: "Czech Koruna",
    icon: "🇨🇿",
    exchangeRate: "-",
  }, 
  "GBP": {
    currencyCode: "GBP",
    currencyName: "Great British Pound",
    icon: "🇬🇧",
    exchangeRate: "-",
  }, 
  "CLP": {
    currencyCode: "CLP",
    currencyName: "Chilean Peso",
    icon: "🇨🇱",
    exchangeRate: "-",
  },
  "DKK": {
    currencyCode: "DKK",
    currencyName: "Danish Krone",
    icon: "🇩🇰",
    exchangeRate: "-",
  }, 
  "EGP": {
    currencyCode: "EGP",
    currencyName: "Egyptian Pound",
    icon: "🇪🇬",
    exchangeRate: "-",
  }, 
  "EUR": {
    currencyCode: "EUR",
    currencyName: "Euro",
    icon: "🇪🇺",
    exchangeRate: "-",
  },
  "HKD": {
    currencyCode: "HKD",
    currencyName: "Hong Kong Dollar",
    icon: "🇭🇰",
    exchangeRate: "-",
  }, 
  "HUF": {
    currencyCode: "HUF",
    currencyName: "Hungarian Forint",
    icon: "🇭🇺",
    exchangeRate: "-",
  }, 
  "INR": {
    currencyCode: "INR",
    currencyName: "Indian Rupee",
    icon: "🇮🇳",
    exchangeRate: "-",
  }, 
  "IDR": {
    currencyCode: "IDR",
    currencyName: "Indonesian Rupiah",
    icon: "🇮🇩",
    exchangeRate: "-",
  }, 
  "ISK": {
    currencyCode: "ISK",
    currencyName: "Icelandic Krona",
    icon: "🇮🇸",
    exchangeRate: "-",
  }, 
  "ILS": {
    currencyCode: "ILS",
    currencyName: "Israeli Shekel",
    icon: "🇮🇱",
    exchangeRate: "-",
  }, 
  "JPY": {
    currencyCode: "JPY",
    currencyName: "Japanese Yen",
    icon: "🇯🇵",
    exchangeRate: "-",
  }, 
  "JOD": {
    currencyCode: "JOD",
    currencyName: "Jordanian Dinar",
    icon: "🇯🇴",
    exchangeRate: "-",
  }, 
  "KES": {
    currencyCode: "KES",
    currencyName: "Kenyan Shilling",
    icon: "🇰🇪",
    exchangeRate: "-",
  }, 
  "KRW": {
    currencyCode: "KRW",
    currencyName: "South Korean Won",
    icon: "🇰🇷",
    exchangeRate: "-",
  }, 
  "HRK": {
    currencyCode: "HRK",
    currencyName: "Croatian Kuna",
    icon: "🇭🇷",
    exchangeRate: "-",
  }, 
  "LKR": {
    currencyCode: "LKR",
    currencyName: "Sri Lankan Rupee",
    icon: "🇱🇰",
    exchangeRate: "-",
  }, 
  "MYR": {
    currencyCode: "MYR",
    currencyName: "Malaysian Ringgit",
    icon: "🇲🇾",
    exchangeRate: "-",
  }, 
  "MAD": {
    currencyCode: "MAD",
    currencyName: "Moroccan Diram",
    icon: "🇲🇦",
    exchangeRate: "-",
  }, 
  "MUR": {
    currencyCode: "MUR",
    currencyName: "Mauritian Rupee",
    icon: "🇲🇺",
    exchangeRate: "-",
  }, 
  "MXN": {
    currencyCode: "MXN",
    currencyName: "Mexican Peso",
    icon: "🇲🇽",
    exchangeRate: "-",
  }, 
  "NOK": {
    currencyCode: "NOK",
    currencyName: "Norwegian Krone",
    icon: "🇳🇴",
    exchangeRate: "-",
  }, 
  "NZD": {
    currencyCode: "NZD",
    currencyName: "New Zealand Dollar",
    icon: "🇳🇿",
    exchangeRate: "-",
  }, 
  "OMR": {
    currencyCode: "OMR",
    currencyName: "Omani Rial",
    icon: "🇴🇲",
    exchangeRate: "-",
  }, 
  "PHP": {
    currencyCode: "PHP",
    currencyName: "Philippine Peso",
    icon: "🇵🇭",
    exchangeRate: "-",
  }, 
  "PLN": {
    currencyCode: "PLN",
    currencyName: "Polish Zloty",
    icon: "🇵🇱",
    exchangeRate: "-",
  }, 
  "QAR": {
    currencyCode: "QAR",
    currencyName: "Qatari Riyal",
    icon: "🇶🇦",
    exchangeRate: "-",
  }, 
  "RON": {
    currencyCode: "RON",
    currencyName: "Romanian New Leu",
    icon: "🇷🇴",
    exchangeRate: "-",
  }, 
  "RUB": {
    currencyCode: "RUB",
    currencyName: "Russian Ruble",
    icon: "🇷🇺",
    exchangeRate: "-",
  }, 
  "SAR": {
    currencyCode: "SAR",
    currencyName: "Saudi Arabian Riyal",
    icon: "🇸🇦",
    exchangeRate: "-",
  }, 
  "SEK": {
    currencyCode: "SEK",
    currencyName: "Swedish Krona",
    icon: "🇸🇪",
    exchangeRate: "-",
  }, 
  "SGD": {
    currencyCode: "SGD",
    currencyName: "Singapore Dollar",
    icon: "🇸🇬",
    exchangeRate: "-",
  }, 
  "TWD": {
    currencyCode: "TWD",
    currencyName: "Taiiwan New Dollar",
    icon: "🇹🇼",
    exchangeRate: "-",
  }, 
  "THB": {
    currencyCode: "THB",
    currencyName: "Thai Baht",
    icon: "🇹🇭",
    exchangeRate: "-",
  }, 
  "TRY": {
    currencyCode: "TRY",
    currencyName: "Turkish Lira",
    icon: "🇹🇷",
    exchangeRate: "-",
  }, 
  "UAH": {
    currencyCode: "UAH",
    currencyName: "Ukrainian Hryvnia",
    icon: "🇺🇦",
    exchangeRate: "-",
  }, 
  "USD": {
    currencyCode: "USD",
    currencyName: "US Dollar",
    icon: "🇺🇸",
    exchangeRate: "-",
  },
  "ZAR": {
    currencyCode: "ZAR",
    currencyName: "South African Rand",
    icon: "🇿🇼",
    exchangeRate: "-",
  }
}